# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sportorg.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!
import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(880, 474)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks|QtWidgets.QMainWindow.ForceTabbedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 25))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 21, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 0, 21, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.verticalLayout.addWidget(self.groupBox_3)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.EntryTab = QtWidgets.QWidget()
        self.EntryTab.setAcceptDrops(False)
        self.EntryTab.setToolTip("")
        self.EntryTab.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.EntryTab.setAutoFillBackground(False)
        self.EntryTab.setObjectName("EntryTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.EntryTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.EntrySplitter = QtWidgets.QSplitter(self.EntryTab)
        self.EntrySplitter.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.EntrySplitter.setAutoFillBackground(True)
        self.EntrySplitter.setOrientation(QtCore.Qt.Horizontal)
        self.EntrySplitter.setObjectName("EntrySplitter")
        self.layoutWidget_3 = QtWidgets.QWidget(self.EntrySplitter)
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.EntryDetails = QtWidgets.QFormLayout(self.layoutWidget_3)
        self.EntryDetails.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.EntryDetails.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.EntryDetails.setFormAlignment(QtCore.Qt.AlignCenter)
        self.EntryDetails.setContentsMargins(0, 0, 0, 0)
        self.EntryDetails.setHorizontalSpacing(1)
        self.EntryDetails.setObjectName("EntryDetails")
        self.EntryNameLabel = QtWidgets.QLabel(self.layoutWidget_3)
        self.EntryNameLabel.setObjectName("EntryNameLabel")
        self.EntryDetails.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.EntryNameLabel)
        self.EntryNameEdit = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.EntryNameEdit.setObjectName("EntryNameEdit")
        self.EntryDetails.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.EntryNameEdit)
        self.EntryGroupLabel = QtWidgets.QLabel(self.layoutWidget_3)
        self.EntryGroupLabel.setObjectName("EntryGroupLabel")
        self.EntryDetails.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.EntryGroupLabel)
        self.EntryGroupCombo = QtWidgets.QComboBox(self.layoutWidget_3)
        self.EntryGroupCombo.setObjectName("EntryGroupCombo")
        self.EntryDetails.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.EntryGroupCombo)
        self.EntryTeamLabel = QtWidgets.QLabel(self.layoutWidget_3)
        self.EntryTeamLabel.setObjectName("EntryTeamLabel")
        self.EntryDetails.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.EntryTeamLabel)
        self.EntryTeamCombo = QtWidgets.QComboBox(self.layoutWidget_3)
        self.EntryTeamCombo.setObjectName("EntryTeamCombo")
        self.EntryDetails.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.EntryTeamCombo)
        self.EntryYearLabel = QtWidgets.QLabel(self.layoutWidget_3)
        self.EntryYearLabel.setObjectName("EntryYearLabel")
        self.EntryDetails.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.EntryYearLabel)
        self.EntryYearSpinBox = QtWidgets.QSpinBox(self.layoutWidget_3)
        self.EntryYearSpinBox.setReadOnly(False)
        self.EntryYearSpinBox.setMinimum(1900)
        self.EntryYearSpinBox.setMaximum(2070)
        self.EntryYearSpinBox.setProperty("value", 1900)
        self.EntryYearSpinBox.setObjectName("EntryYearSpinBox")
        self.EntryDetails.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.EntryYearSpinBox)
        self.EntryBirthDayLabel = QtWidgets.QLabel(self.layoutWidget_3)
        self.EntryBirthDayLabel.setObjectName("EntryBirthDayLabel")
        self.EntryDetails.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.EntryBirthDayLabel)
        self.EntryBirthDayEdit = QtWidgets.QDateEdit(self.layoutWidget_3)
        self.EntryBirthDayEdit.setObjectName("EntryBirthDayEdit")
        self.EntryDetails.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.EntryBirthDayEdit)
        self.EntryQualLabel = QtWidgets.QLabel(self.layoutWidget_3)
        self.EntryQualLabel.setObjectName("EntryQualLabel")
        self.EntryDetails.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.EntryQualLabel)
        self.EntryQualCombo = QtWidgets.QComboBox(self.layoutWidget_3)
        self.EntryQualCombo.setObjectName("EntryQualCombo")
        self.EntryDetails.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.EntryQualCombo)
        self.EntryLine = QtWidgets.QFrame(self.layoutWidget_3)
        self.EntryLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.EntryLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.EntryLine.setObjectName("EntryLine")
        self.EntryDetails.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.EntryLine)
        self.EntryStartLabel = QtWidgets.QLabel(self.layoutWidget_3)
        self.EntryStartLabel.setObjectName("EntryStartLabel")
        self.EntryDetails.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.EntryStartLabel)
        self.EntryStartEdit = QtWidgets.QTimeEdit(self.layoutWidget_3)
        self.EntryStartEdit.setObjectName("EntryStartEdit")
        self.EntryDetails.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.EntryStartEdit)
        self.EntryBibNumber = QtWidgets.QLabel(self.layoutWidget_3)
        self.EntryBibNumber.setObjectName("EntryBibNumber")
        self.EntryDetails.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.EntryBibNumber)
        self.EntryBibSpinBox = QtWidgets.QSpinBox(self.layoutWidget_3)
        self.EntryBibSpinBox.setMinimum(1900)
        self.EntryBibSpinBox.setMaximum(2070)
        self.EntryBibSpinBox.setProperty("value", 1900)
        self.EntryBibSpinBox.setObjectName("EntryBibSpinBox")
        self.EntryDetails.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.EntryBibSpinBox)
        self.EntryTable = QtWidgets.QTableWidget(self.EntrySplitter)
        self.EntryTable.setObjectName("EntryTable")
        self.EntryTable.setColumnCount(15)
        self.EntryTable.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.EntryTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.EntryTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.EntryTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.EntryTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.EntryTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.EntryTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.EntryTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.EntryTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.EntryTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.EntryTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.EntryTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.EntryTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.EntryTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.EntryTable.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.EntryTable.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.EntryTable.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.EntryTable.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.EntryTable.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.EntryTable.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.EntryTable.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.EntryTable.setHorizontalHeaderItem(14, item)
        self.gridLayout_2.addWidget(self.EntrySplitter, 0, 0, 1, 1)
        self.tabWidget.addTab(self.EntryTab, "")
        self.ResultTab = QtWidgets.QWidget()
        self.ResultTab.setObjectName("ResultTab")
        self.gridLayout = QtWidgets.QGridLayout(self.ResultTab)
        self.gridLayout.setObjectName("gridLayout")
        self.ResultSplitter = QtWidgets.QSplitter(self.ResultTab)
        self.ResultSplitter.setOrientation(QtCore.Qt.Horizontal)
        self.ResultSplitter.setObjectName("ResultSplitter")
        self.ResultLeftPart = QtWidgets.QFrame(self.ResultSplitter)
        self.ResultLeftPart.setMaximumSize(QtCore.QSize(240, 16777215))
        self.ResultLeftPart.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ResultLeftPart.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ResultLeftPart.setObjectName("ResultLeftPart")
        self.ResultCourseGroupBox = QtWidgets.QGroupBox(self.ResultLeftPart)
        self.ResultCourseGroupBox.setGeometry(QtCore.QRect(1, 1, 119, 399))
        self.ResultCourseGroupBox.setObjectName("ResultCourseGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.ResultCourseGroupBox)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ResultCourseForm = QtWidgets.QFormLayout()
        self.ResultCourseForm.setObjectName("ResultCourseForm")
        self.ResultCourseNameLabel = QtWidgets.QLabel(self.ResultCourseGroupBox)
        self.ResultCourseNameLabel.setObjectName("ResultCourseNameLabel")
        self.ResultCourseForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.ResultCourseNameLabel)
        self.ResultCourseNameEdit = QtWidgets.QLineEdit(self.ResultCourseGroupBox)
        self.ResultCourseNameEdit.setObjectName("ResultCourseNameEdit")
        self.ResultCourseForm.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ResultCourseNameEdit)
        self.ResultCourseLengthLabel = QtWidgets.QLabel(self.ResultCourseGroupBox)
        self.ResultCourseLengthLabel.setObjectName("ResultCourseLengthLabel")
        self.ResultCourseForm.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.ResultCourseLengthLabel)
        self.ResultCourseLengthEdit = QtWidgets.QLineEdit(self.ResultCourseGroupBox)
        self.ResultCourseLengthEdit.setObjectName("ResultCourseLengthEdit")
        self.ResultCourseForm.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ResultCourseLengthEdit)
        self.verticalLayout_2.addLayout(self.ResultCourseForm)
        self.ResultCourseDetails = QtWidgets.QTextBrowser(self.ResultCourseGroupBox)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.ResultCourseDetails.setFont(font)
        self.ResultCourseDetails.setObjectName("ResultCourseDetails")
        self.verticalLayout_2.addWidget(self.ResultCourseDetails)
        self.ResultChipGroupBox = QtWidgets.QGroupBox(self.ResultLeftPart)
        self.ResultChipGroupBox.setGeometry(QtCore.QRect(120, 1, 119, 399))
        self.ResultChipGroupBox.setObjectName("ResultChipGroupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.ResultChipGroupBox)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ResultChipForm = QtWidgets.QFormLayout()
        self.ResultChipForm.setObjectName("ResultChipForm")
        self.ResultChipStartLabel = QtWidgets.QLabel(self.ResultChipGroupBox)
        self.ResultChipStartLabel.setObjectName("ResultChipStartLabel")
        self.ResultChipForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.ResultChipStartLabel)
        self.ResultChipStartEdit = QtWidgets.QLineEdit(self.ResultChipGroupBox)
        self.ResultChipStartEdit.setObjectName("ResultChipStartEdit")
        self.ResultChipForm.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ResultChipStartEdit)
        self.ResultChipFinishLabel = QtWidgets.QLabel(self.ResultChipGroupBox)
        self.ResultChipFinishLabel.setObjectName("ResultChipFinishLabel")
        self.ResultChipForm.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.ResultChipFinishLabel)
        self.ResultChipFinishEdit = QtWidgets.QLineEdit(self.ResultChipGroupBox)
        self.ResultChipFinishEdit.setObjectName("ResultChipFinishEdit")
        self.ResultChipForm.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ResultChipFinishEdit)
        self.verticalLayout_3.addLayout(self.ResultChipForm)
        self.ResultChipDetails = QtWidgets.QTextBrowser(self.ResultChipGroupBox)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.ResultChipDetails.setFont(font)
        self.ResultChipDetails.setObjectName("ResultChipDetails")
        self.verticalLayout_3.addWidget(self.ResultChipDetails)
        self.ResultTable = QtWidgets.QTableWidget(self.ResultSplitter)
        self.ResultTable.setObjectName("ResultTable")
        self.ResultTable.setColumnCount(12)
        self.ResultTable.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.ResultTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ResultTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ResultTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ResultTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.ResultTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.ResultTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.ResultTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ResultTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ResultTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ResultTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.ResultTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.ResultTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.ResultTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.ResultTable.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.ResultTable.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.ResultTable.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.ResultTable.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.ResultTable.setHorizontalHeaderItem(11, item)
        self.gridLayout.addWidget(self.ResultSplitter, 0, 0, 1, 1)
        self.tabWidget.addTab(self.ResultTab, "")
        self.GroupTab = QtWidgets.QWidget()
        self.GroupTab.setObjectName("GroupTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.GroupTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.GroupTable = QtWidgets.QTableWidget(self.GroupTab)
        self.GroupTable.setObjectName("GroupTable")
        self.GroupTable.setColumnCount(12)
        self.GroupTable.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.GroupTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.GroupTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.GroupTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.GroupTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.GroupTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.GroupTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.GroupTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.GroupTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.GroupTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.GroupTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.GroupTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.GroupTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.GroupTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.GroupTable.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.GroupTable.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.GroupTable.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.GroupTable.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.GroupTable.setHorizontalHeaderItem(11, item)
        self.gridLayout_3.addWidget(self.GroupTable, 0, 0, 1, 1)
        self.tabWidget.addTab(self.GroupTab, "")
        self.CourseTab = QtWidgets.QWidget()
        self.CourseTab.setObjectName("CourseTab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.CourseTab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.CourseTable = QtWidgets.QTableWidget(self.CourseTab)
        self.CourseTable.setObjectName("CourseTable")
        self.CourseTable.setColumnCount(8)
        self.CourseTable.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.CourseTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CourseTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.CourseTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.CourseTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.CourseTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.CourseTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.CourseTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CourseTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.CourseTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.CourseTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.CourseTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.CourseTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.CourseTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.CourseTable.setHorizontalHeaderItem(7, item)
        self.gridLayout_4.addWidget(self.CourseTable, 0, 0, 1, 1)
        self.tabWidget.addTab(self.CourseTab, "")
        self.TeamTab = QtWidgets.QWidget()
        self.TeamTab.setObjectName("TeamTab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.TeamTab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.TeamTable = QtWidgets.QTableWidget(self.TeamTab)
        self.TeamTable.setObjectName("TeamTable")
        self.TeamTable.setColumnCount(5)
        self.TeamTable.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.TeamTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TeamTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TeamTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TeamTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TeamTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.TeamTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.TeamTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TeamTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TeamTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TeamTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TeamTable.setHorizontalHeaderItem(4, item)
        self.gridLayout_5.addWidget(self.TeamTable, 0, 0, 1, 1)
        self.tabWidget.addTab(self.TeamTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 880, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuImport = QtWidgets.QMenu(self.menuFile)
        self.menuImport.setObjectName("menuImport")
        self.menuStart_preparation = QtWidgets.QMenu(self.menubar)
        self.menuStart_preparation.setObjectName("menuStart_preparation")
        self.menuRace = QtWidgets.QMenu(self.menubar)
        self.menuRace.setObjectName("menuRace")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuResults = QtWidgets.QMenu(self.menubar)
        self.menuResults.setObjectName("menuResults")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuService = QtWidgets.QMenu(self.menubar)
        self.menuService.setObjectName("menuService")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionNew_Race = QtWidgets.QAction(MainWindow)
        self.actionNew_Race.setObjectName("actionNew_Race")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionOpen_Resent = QtWidgets.QAction(MainWindow)
        self.actionOpen_Resent.setObjectName("actionOpen_Resent")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionEvent_Settings = QtWidgets.QAction(MainWindow)
        self.actionEvent_Settings.setObjectName("actionEvent_Settings")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionCSV_Winorient = QtWidgets.QAction(MainWindow)
        self.actionCSV_Winorient.setObjectName("actionCSV_Winorient")
        self.actionWDB_Winorient = QtWidgets.QAction(MainWindow)
        self.actionWDB_Winorient.setObjectName("actionWDB_Winorient")
        self.actionIOF_XML_v3 = QtWidgets.QAction(MainWindow)
        self.actionIOF_XML_v3.setObjectName("actionIOF_XML_v3")
        self.actionCVS = QtWidgets.QAction(MainWindow)
        self.actionCVS.setObjectName("actionCVS")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout_us = QtWidgets.QAction(MainWindow)
        self.actionAbout_us.setObjectName("actionAbout_us")
        self.menuImport.addAction(self.actionCVS)
        self.menuImport.addAction(self.actionCSV_Winorient)
        self.menuImport.addAction(self.actionWDB_Winorient)
        self.menuImport.addAction(self.actionIOF_XML_v3)
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionNew_Race)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionOpen_Resent)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSettings)
        self.menuFile.addAction(self.actionEvent_Settings)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuImport.menuAction())
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionAbout_us)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuStart_preparation.menuAction())
        self.menubar.addAction(self.menuRace.menuAction())
        self.menubar.addAction(self.menuResults.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuService.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "A"))
        self.pushButton_2.setText(_translate("MainWindow", "B"))
        self.EntryNameLabel.setText(_translate("MainWindow", "Name"))
        self.EntryGroupLabel.setText(_translate("MainWindow", "Group"))
        self.EntryTeamLabel.setText(_translate("MainWindow", "Team"))
        self.EntryYearLabel.setText(_translate("MainWindow", "Year"))
        self.EntryBirthDayLabel.setText(_translate("MainWindow", "Birth day"))
        self.EntryQualLabel.setText(_translate("MainWindow", "Qual"))
        self.EntryStartLabel.setText(_translate("MainWindow", "Start"))
        self.EntryBibNumber.setText(_translate("MainWindow", "Bib"))
        item = self.EntryTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.EntryTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.EntryTable.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.EntryTable.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.EntryTable.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.EntryTable.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.EntryTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Last Name"))
        item = self.EntryTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.EntryTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Sex"))
        item = self.EntryTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Group"))
        item = self.EntryTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Team"))
        item = self.EntryTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Year of birth"))
        item = self.EntryTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Bib"))
        item = self.EntryTable.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Start time"))
        item = self.EntryTable.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Card"))
        item = self.EntryTable.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Rented cart"))
        item = self.EntryTable.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Paid"))
        item = self.EntryTable.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Personal"))
        item = self.EntryTable.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "Comment"))
        item = self.EntryTable.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "ruscod_id"))
        item = self.EntryTable.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "wre_id"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.EntryTab), _translate("MainWindow", "Start preparation"))
        self.ResultCourseGroupBox.setTitle(_translate("MainWindow", "Course"))
        self.ResultCourseNameLabel.setText(_translate("MainWindow", "Name"))
        self.ResultCourseLengthLabel.setText(_translate("MainWindow", "Length"))
        self.ResultCourseDetails.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Courier New\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt; font-weight:600;\"> 1   31    755</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt; font-weight:600; color:#ff0000;\"> 2   32    102 </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt; font-weight:600;\"> 3   33    145</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt; font-weight:600; color:#ff0000;\"> 4   34  1345</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt; font-weight:600; color:#000000;\"> 5   35      56</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:9pt; font-weight:600; color:#000000;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt; font-weight:600; color:#000000;\"> 6 100    200</span></p></body></html>"))
        self.ResultChipGroupBox.setTitle(_translate("MainWindow", "Chip"))
        self.ResultChipStartLabel.setText(_translate("MainWindow", "Start"))
        self.ResultChipFinishLabel.setText(_translate("MainWindow", "Finish"))
        self.ResultChipDetails.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Courier New\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt; font-weight:600;\"> 1  31  12:02:34</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt; font-weight:600; color:#ff0000;\"> 2  39  12:03:33</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt; font-weight:600;\"> 3  33  12:04:35</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt; font-weight:600; color:#ff0000;\"> 4  34  - - - - - - </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt; font-weight:600; color:#000000;\"> 5  35  12:15:00</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt; font-weight:600; color:#aa007f;\">     90  12:16:11</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt; font-weight:600; color:#000000;\">    </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt; font-weight:600; color:#000000;\"> 6 100 12:17:12</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:9pt; font-weight:600; color:#000000;\"><br /></p></body></html>"))
        item = self.ResultTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.ResultTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.ResultTable.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.ResultTable.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.ResultTable.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.ResultTable.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.ResultTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Bib"))
        item = self.ResultTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Last Name"))
        item = self.ResultTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Name"))
        item = self.ResultTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Card"))
        item = self.ResultTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Place"))
        item = self.ResultTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Diff"))
        item = self.ResultTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Finish time"))
        item = self.ResultTable.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Start time"))
        item = self.ResultTable.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Penalty"))
        item = self.ResultTable.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Status"))
        item = self.ResultTable.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Group"))
        item = self.ResultTable.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Team"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ResultTab), _translate("MainWindow", "Race Results"))
        item = self.GroupTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.GroupTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.GroupTable.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.GroupTable.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.GroupTable.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.GroupTable.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.GroupTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.GroupTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Description"))
        item = self.GroupTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Course"))
        item = self.GroupTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Sex"))
        item = self.GroupTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Age from"))
        item = self.GroupTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Age to"))
        item = self.GroupTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Fee"))
        item = self.GroupTable.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Max time"))
        item = self.GroupTable.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Qualification rules"))
        item = self.GroupTable.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Start interval"))
        item = self.GroupTable.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Start corridor"))
        item = self.GroupTable.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Order in corridor"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.GroupTab), _translate("MainWindow", "Groups"))
        item = self.CourseTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.CourseTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.CourseTable.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.CourseTable.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.CourseTable.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.CourseTable.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.CourseTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.CourseTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Description"))
        item = self.CourseTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Course family"))
        item = self.CourseTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Length"))
        item = self.CourseTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Climb"))
        item = self.CourseTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Number of controls"))
        item = self.CourseTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Race"))
        item = self.CourseTable.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Controls"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.CourseTab), _translate("MainWindow", "Courses"))
        item = self.TeamTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.TeamTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.TeamTable.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.TeamTable.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.TeamTable.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.TeamTable.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.TeamTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.TeamTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Addres"))
        item = self.TeamTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Region"))
        item = self.TeamTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Новый столбец"))
        item = self.TeamTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Concats person"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TeamTab), _translate("MainWindow", "Teams"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuImport.setTitle(_translate("MainWindow", "Import"))
        self.menuStart_preparation.setTitle(_translate("MainWindow", "Start preparation"))
        self.menuRace.setTitle(_translate("MainWindow", "Race"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuResults.setTitle(_translate("MainWindow", "Results"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.menuService.setTitle(_translate("MainWindow", "Service"))
        self.menuOptions.setTitle(_translate("MainWindow", "Options"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionQuit.setText(_translate("MainWindow", "Exit"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionNew_Race.setText(_translate("MainWindow", "New Race"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as"))
        self.actionOpen_Resent.setText(_translate("MainWindow", "Open Recent"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionEvent_Settings.setText(_translate("MainWindow", "Event Settings"))
        self.actionExport.setText(_translate("MainWindow", "Export"))
        self.actionCSV_Winorient.setText(_translate("MainWindow", "CSV Winorient"))
        self.actionWDB_Winorient.setText(_translate("MainWindow", "WDB Winorient"))
        self.actionIOF_XML_v3.setText(_translate("MainWindow", "IOF XML v3"))
        self.actionCVS.setText(_translate("MainWindow", "CVS "))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionAbout_us.setText(_translate("MainWindow", "About us"))

def main(argv):
    app = QApplication(argv)
    mw = QMainWindow()
    obj = Ui_MainWindow()
    obj.setupUi(mw)
    mw.show()
    sys.exit(app.exec())


if __name__ == '__main__':
    main(sys.argv)
