# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_start_preparation.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!
import sys
from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QApplication, QDialog


class Ui_start_preparation_dialog(object):
    def setupUi(self, start_preparation_dialog):
        start_preparation_dialog.setObjectName("start_preparation_dialog")
        start_preparation_dialog.resize(639, 317)
        self.button_box = QtWidgets.QDialogButtonBox(start_preparation_dialog)
        self.button_box.setGeometry(QtCore.QRect(40, 280, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.reserve_group_box = QtWidgets.QGroupBox(start_preparation_dialog)
        self.reserve_group_box.setGeometry(QtCore.QRect(8, 0, 311, 121))
        self.reserve_group_box.setObjectName("reserve_group_box")
        self.widget = QtWidgets.QWidget(self.reserve_group_box)
        self.widget.setGeometry(QtCore.QRect(19, 20, 254, 97))
        self.widget.setObjectName("widget")
        self.reserve_layout = QtWidgets.QFormLayout(self.widget)
        self.reserve_layout.setContentsMargins(0, 0, 0, 0)
        self.reserve_layout.setObjectName("reserve_layout")
        self.reserve_prefix_label = QtWidgets.QLabel(self.widget)
        self.reserve_prefix_label.setObjectName("reserve_prefix_label")
        self.reserve_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.reserve_prefix_label)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.reserve_layout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.reserve_group_count_label = QtWidgets.QLabel(self.widget)
        self.reserve_group_count_label.setObjectName("reserve_group_count_label")
        self.reserve_layout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.reserve_group_count_label)
        self.reserve_group_count_spin_box = QtWidgets.QSpinBox(self.widget)
        self.reserve_group_count_spin_box.setEnabled(False)
        self.reserve_group_count_spin_box.setObjectName("reserve_group_count_spin_box")
        self.reserve_layout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.reserve_group_count_spin_box)
        self.reserve_group_percent_label = QtWidgets.QLabel(self.widget)
        self.reserve_group_percent_label.setObjectName("reserve_group_percent_label")
        self.reserve_layout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.reserve_group_percent_label)
        self.reserve_group_percent_spin_box = QtWidgets.QSpinBox(self.widget)
        self.reserve_group_percent_spin_box.setEnabled(False)
        self.reserve_group_percent_spin_box.setMaximum(100)
        self.reserve_group_percent_spin_box.setSingleStep(5)
        self.reserve_group_percent_spin_box.setObjectName("reserve_group_percent_spin_box")
        self.reserve_layout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.reserve_group_percent_spin_box)
        self.reserve_check_box = QtWidgets.QCheckBox(self.widget)
        self.reserve_check_box.setObjectName("reserve_check_box")
        self.reserve_layout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.reserve_check_box)
        self.progress_bar = QtWidgets.QProgressBar(start_preparation_dialog)
        self.progress_bar.setGeometry(QtCore.QRect(10, 250, 621, 23))
        self.progress_bar.setProperty("value", 24)
        self.progress_bar.setObjectName("progress_bar")
        self.draw_group_box = QtWidgets.QGroupBox(start_preparation_dialog)
        self.draw_group_box.setGeometry(QtCore.QRect(323, 0, 311, 121))
        self.draw_group_box.setObjectName("draw_group_box")
        self.widget1 = QtWidgets.QWidget(self.draw_group_box)
        self.widget1.setGeometry(QtCore.QRect(20, 16, 128, 88))
        self.widget1.setObjectName("widget1")
        self.draw_layout = QtWidgets.QFormLayout(self.widget1)
        self.draw_layout.setContentsMargins(0, 0, 0, 0)
        self.draw_layout.setObjectName("draw_layout")
        self.draw_check_box = QtWidgets.QCheckBox(self.widget1)
        self.draw_check_box.setObjectName("draw_check_box")
        self.draw_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.draw_check_box)
        self.draw_groups_check_box = QtWidgets.QCheckBox(self.widget1)
        self.draw_groups_check_box.setEnabled(False)
        self.draw_groups_check_box.setObjectName("draw_groups_check_box")
        self.draw_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.draw_groups_check_box)
        self.draw_teams_check_box = QtWidgets.QCheckBox(self.widget1)
        self.draw_teams_check_box.setEnabled(False)
        self.draw_teams_check_box.setObjectName("draw_teams_check_box")
        self.draw_layout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.draw_teams_check_box)
        self.draw_regions_check_box = QtWidgets.QCheckBox(self.widget1)
        self.draw_regions_check_box.setEnabled(False)
        self.draw_regions_check_box.setObjectName("draw_regions_check_box")
        self.draw_layout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.draw_regions_check_box)
        self.start_group_box = QtWidgets.QGroupBox(start_preparation_dialog)
        self.start_group_box.setGeometry(QtCore.QRect(8, 120, 311, 121))
        self.start_group_box.setObjectName("start_group_box")
        self.widget2 = QtWidgets.QWidget(self.start_group_box)
        self.widget2.setGeometry(QtCore.QRect(18, 16, 210, 94))
        self.widget2.setObjectName("widget2")
        self.start_layout = QtWidgets.QFormLayout(self.widget2)
        self.start_layout.setContentsMargins(0, 0, 0, 0)
        self.start_layout.setObjectName("start_layout")
        self.start_check_box = QtWidgets.QCheckBox(self.widget2)
        self.start_check_box.setObjectName("start_check_box")
        self.start_layout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.start_check_box)
        self.start_first_label = QtWidgets.QLabel(self.widget2)
        self.start_first_label.setObjectName("start_first_label")
        self.start_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.start_first_label)
        self.start_first_time_edit = QtWidgets.QTimeEdit(self.widget2)
        self.start_first_time_edit.setEnabled(False)
        self.start_first_time_edit.setObjectName("start_first_time_edit")
        self.start_layout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.start_first_time_edit)
        self.start_interval_radio_button = QtWidgets.QRadioButton(self.widget2)
        self.start_interval_radio_button.setChecked(True)
        self.start_interval_radio_button.setObjectName("start_interval_radio_button")
        self.start_layout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.start_interval_radio_button)
        self.start_interval_time_edit = QtWidgets.QTimeEdit(self.widget2)
        self.start_interval_time_edit.setEnabled(False)
        self.start_interval_time_edit.setObjectName("start_interval_time_edit")
        self.start_layout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.start_interval_time_edit)
        self.start_group_settings_radion_button = QtWidgets.QRadioButton(self.widget2)
        self.start_group_settings_radion_button.setEnabled(False)
        self.start_group_settings_radion_button.setChecked(False)
        self.start_group_settings_radion_button.setObjectName("start_group_settings_radion_button")
        self.start_layout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.start_group_settings_radion_button)
        self.numbers_group_box = QtWidgets.QGroupBox(start_preparation_dialog)
        self.numbers_group_box.setGeometry(QtCore.QRect(322, 120, 311, 121))
        self.numbers_group_box.setObjectName("numbers_group_box")
        self.widget3 = QtWidgets.QWidget(self.numbers_group_box)
        self.widget3.setGeometry(QtCore.QRect(19, 17, 218, 70))
        self.widget3.setObjectName("widget3")
        self.numbers_vert_layout = QtWidgets.QVBoxLayout(self.widget3)
        self.numbers_vert_layout.setContentsMargins(0, 0, 0, 0)
        self.numbers_vert_layout.setObjectName("numbers_vert_layout")
        self.numbers_check_box = QtWidgets.QCheckBox(self.widget3)
        self.numbers_check_box.setObjectName("numbers_check_box")
        self.numbers_vert_layout.addWidget(self.numbers_check_box)
        self.numbers_interval_hor_layout = QtWidgets.QHBoxLayout()
        self.numbers_interval_hor_layout.setObjectName("numbers_interval_hor_layout")
        self.numbers_interval_radio_button = QtWidgets.QRadioButton(self.widget3)
        self.numbers_interval_radio_button.setChecked(True)
        self.numbers_interval_radio_button.setObjectName("numbers_interval_radio_button")
        self.numbers_interval_hor_layout.addWidget(self.numbers_interval_radio_button)
        self.numbers_first_spin_box = QtWidgets.QSpinBox(self.widget3)
        self.numbers_first_spin_box.setEnabled(False)
        self.numbers_first_spin_box.setObjectName("numbers_first_spin_box")
        self.numbers_interval_hor_layout.addWidget(self.numbers_first_spin_box)
        self.numbers_interval_label = QtWidgets.QLabel(self.widget3)
        self.numbers_interval_label.setObjectName("numbers_interval_label")
        self.numbers_interval_hor_layout.addWidget(self.numbers_interval_label)
        self.numbers_interval_spin_box = QtWidgets.QSpinBox(self.widget3)
        self.numbers_interval_spin_box.setEnabled(False)
        self.numbers_interval_spin_box.setObjectName("numbers_interval_spin_box")
        self.numbers_interval_hor_layout.addWidget(self.numbers_interval_spin_box)
        self.numbers_vert_layout.addLayout(self.numbers_interval_hor_layout)
        self.numbers_minute_radio_button = QtWidgets.QRadioButton(self.widget3)
        self.numbers_minute_radio_button.setEnabled(False)
        self.numbers_minute_radio_button.setChecked(False)
        self.numbers_minute_radio_button.setObjectName("numbers_minute_radio_button")
        self.numbers_vert_layout.addWidget(self.numbers_minute_radio_button)
        self.numbers_minute_radio_button.raise_()
        self.numbers_interval_radio_button.raise_()
        self.numbers_first_spin_box.raise_()
        self.numbers_interval_label.raise_()
        self.numbers_interval_spin_box.raise_()
        self.numbers_interval_radio_button.raise_()
        self.button_box.raise_()
        self.reserve_group_box.raise_()
        self.progress_bar.raise_()
        self.draw_group_box.raise_()
        self.start_group_box.raise_()
        self.numbers_group_box.raise_()

        self.retranslateUi(start_preparation_dialog)
        self.button_box.accepted.connect(start_preparation_dialog.accept)
        self.button_box.rejected.connect(start_preparation_dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(start_preparation_dialog)

    def retranslateUi(self, start_preparation_dialog):
        _translate = QtCore.QCoreApplication.translate
        start_preparation_dialog.setWindowTitle(_translate("start_preparation_dialog", "Dialog"))
        self.reserve_group_box.setTitle(_translate("start_preparation_dialog", "Reserves insert"))
        self.reserve_prefix_label.setText(_translate("start_preparation_dialog", "Reserve prefix"))
        self.lineEdit.setText(_translate("start_preparation_dialog", "Reserve"))
        self.reserve_group_count_label.setText(_translate("start_preparation_dialog", "Reserves per group, ps"))
        self.reserve_group_percent_label.setText(_translate("start_preparation_dialog", "Reserves per group, %"))
        self.reserve_check_box.setText(_translate("start_preparation_dialog", "Insert reserves"))
        self.draw_group_box.setTitle(_translate("start_preparation_dialog", "Draw"))
        self.draw_check_box.setText(_translate("start_preparation_dialog", "Draw"))
        self.draw_groups_check_box.setText(_translate("start_preparation_dialog", "Split by start groups"))
        self.draw_teams_check_box.setText(_translate("start_preparation_dialog", "Split by teams"))
        self.draw_regions_check_box.setText(_translate("start_preparation_dialog", "Split by regions"))
        self.start_group_box.setTitle(_translate("start_preparation_dialog", "Start time"))
        self.start_check_box.setText(_translate("start_preparation_dialog", "Change start time"))
        self.start_first_label.setText(_translate("start_preparation_dialog", "First start in corridor"))
        self.start_interval_radio_button.setText(_translate("start_preparation_dialog", "Fixed start interval"))
        self.start_group_settings_radion_button.setText(_translate("start_preparation_dialog", "Take start interval from group settings"))
        self.numbers_group_box.setTitle(_translate("start_preparation_dialog", "Start numbers"))
        self.numbers_check_box.setText(_translate("start_preparation_dialog", "Change start numbers"))
        self.numbers_interval_radio_button.setText(_translate("start_preparation_dialog", "First number "))
        self.numbers_interval_label.setText(_translate("start_preparation_dialog", "interval"))
        self.numbers_minute_radio_button.setText(_translate("start_preparation_dialog", "Number = corridor + minute"))

def main(argv):
    app = QApplication(argv)
    mw = QDialog()
    obj = Ui_start_preparation_dialog()
    obj.setupUi(mw)
    mw.show()
    sys.exit(app.exec())

if __name__ == '__main__':
    main(sys.argv)