name: CI Tests/Lints

on:
  push:
    paths:
      - ".github/workflows/**"
      - "sportorg/**"
      - "tests/**"
      - "uv.lock"
    branches: [ master ]
  pull_request:
    paths:
      - ".github/workflows/**"
      - "sportorg/**"
      - "tests/**"
      - "uv.lock"
    branches: [ master ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: windows-latest
    strategy:
      matrix:
        python_version: [3.8, 3.14]
        architecture: [x64]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
          architecture: ${{ matrix.architecture }}

      - name: Install python dependencies
        run: pip install uv && uv sync --frozen --extra win

      - name: Run linters
        run: uv run poe lint

  test:
    runs-on: windows-latest
    strategy:
      matrix:
        python_version: [3.8, 3.14]
        architecture: [x64]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
          architecture: ${{ matrix.architecture }}

      - name: Install python dependencies
        run: pip install uv && uv sync --frozen --extra win

      - name: Run test
        run: uv run poe test

  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python_version: [3.8]
        architecture: [x64]
    name: Build on Windows ${{ matrix.architecture }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Python
        id: set_up_python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
          architecture: ${{ matrix.architecture }}
      - name: Install python dependencies
        run: pip install uv && uv sync --frozen --extra win
      - name: Generate mo files
        run: uv run poe generate-mo
      - name: Generate version file
        run: uv run poe generate-version
      - name: Build
        run: uv run python builder.py build
      - name: Generate installer
        run: uv run python builder.py bdist_msi
