name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        architecture: [x64]
    name: Build on Windows ${{ matrix.architecture }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        id: set_up_python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
          architecture: ${{ matrix.architecture }}
      - name: Install python dependencies
        run: pip install poetry && poetry install -E win
      - name: Generate mo files
        run: poetry run poe generate-mo
      - name: Build
        run: poetry run python builder.py build
      - name: Generate installer
        run: poetry run python builder.py bdist_msi
      - name: Upload the artifact
        uses: actions/upload-artifact@v4
        with:
          path: dist/*.msi
          name: ${{ runner.os }}-${{ matrix.architecture }}
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/*.msi
