name: Release

on:
  push:
    tags:
      - "v*"
      - "nightly"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        architecture: [x64]
    name: Build on Windows ${{ matrix.architecture }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Python
        id: set_up_python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
          architecture: ${{ matrix.architecture }}
      - name: Install python dependencies
        run: pip install uv && uv sync --frozen --extra win
      - name: Generate mo files
        run: uv run poe generate-mo
      - name: Generate version file
        run: uv run poe generate-version
      - name: Build
        run: uv run python builder.py build
      - name: Generate installer
        run: uv run python builder.py bdist_msi
      - name: Upload the artifact
        uses: actions/upload-artifact@v4
        with:
          path: dist/*.msi
          name: ${{ runner.os }}-${{ matrix.architecture }}
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          make_latest: ${{ github.ref_name != 'nightly' }}
          files: |
            dist/*.msi
